clean up install

diff --git a/aliases b/aliases
--- a/aliases
+++ b/aliases
@@ -44,7 +44,7 @@
   alias hideall='defaults write com.apple.finder AppleShowAllFiles NO && killall Finder'
 
 # cat is good. cat with colors is better
-# alias cat='pygmentize -O style=monokai -f console256 -g'
+  alias cat='pygmentize -O style=solarizeddark -f console256 -g'
 
 # Get rid of those pesky .DS_Store files recursively
   alias dsclean='find . -type f -name .DS_Store -print0 | xargs -0 rm'
@@ -166,33 +166,73 @@ function ghUpdate() {
 # Extract archives - use: extract <file>
 # Based on http://dotfiles.org/~pseup/.bashrc
 function extract() {
- if [ -z "$1" ]; then
-    # display usage if no parameters given
-    echo "Usage: extract <path/file_name>.<zip|rar|bz2|gz|tar|tbz2|tgz|Z|7z|xz|ex|tar.bz2|tar.gz|tar.xz>"
- else
-    if [ -f "$1" ] ; then
-        # NAME=${1%.*}
-        # mkdir $NAME && cd $NAME
-        case "$1" in
-          *.tar.bz2)   tar xvjf ../"$1"    ;;
-          *.tar.gz)    tar xvzf ../"$1"    ;;
-          *.tar.xz)    tar xvJf ../"$1"    ;;
-          *.lzma)      unlzma ../"$1"      ;;
-          *.bz2)       bunzip2 ../"$1"     ;;
-          *.rar)       unrar x -ad ../"$1" ;;
-          *.gz)        gunzip ../"$1"      ;;
-          *.tar)       tar xvf ../"$1"     ;;
-          *.tbz2)      tar xvjf ../"$1"    ;;
-          *.tgz)       tar xvzf ../"$1"    ;;
-          *.zip)       unzip ../"$1"       ;;
-          *.Z)         uncompress ../"$1"  ;;
-          *.7z)        7z x ../"$1"        ;;
-          *.xz)        unxz ../"$1"        ;;
-          *.exe)       cabextract ../"$1"  ;;
-          *)           echo "extract: '$1' - unknown archive method" ;;
-        esac
-    else
-        echo "'$1' - file does not exist"
+  local remove_archive
+  local success
+  local file_name
+  local extract_dir
+
+  if (( $# == 0 )); then
+    echo "Usage: extract [-option] [file ...]"
+    echo
+    echo Options:
+    echo "    -r, --remove    Remove archive."
+    echo
+    echo "Report bugs to <sorin.ionescu@gmail.com>."
+  fi
+
+  remove_archive=1
+  if [[ "$1" == "-r" ]] || [[ "$1" == "--remove" ]]; then
+    remove_archive=0 
+    shift
+  fi
+
+  while (( $# > 0 )); do
+    if [[ ! -f "$1" ]]; then
+      echo "extract: '$1' is not a valid file" 1>&2
+      shift
+      continue
     fi
-fi
+
+    success=0
+    file_name="$( basename "$1" )"
+    extract_dir="$( echo "$file_name" | sed "s/\.${1##*.}//g" )"
+    case "$1" in
+      (*.tar.gz|*.tgz) [ -z $commands[pigz] ] && tar zxvf "$1" || pigz -dc "$1" | tar xv ;;
+      (*.tar.bz2|*.tbz|*.tbz2) tar xvjf "$1" ;;
+      (*.tar.xz|*.txz) tar --xz --help &> /dev/null \
+        && tar --xz -xvf "$1" \
+        || xzcat "$1" | tar xvf - ;;
+      (*.tar.zma|*.tlz) tar --lzma --help &> /dev/null \
+        && tar --lzma -xvf "$1" \
+        || lzcat "$1" | tar xvf - ;;
+      (*.tar) tar xvf "$1" ;;
+      (*.gz) [ -z $commands[pigz] ] && gunzip "$1" || pigz -d "$1" ;;
+      (*.bz2) bunzip2 "$1" ;;
+      (*.xz) unxz "$1" ;;
+      (*.lzma) unlzma "$1" ;;
+      (*.Z) uncompress "$1" ;;
+      (*.zip|*.war|*.jar|*.sublime-package) unzip "$1" -d $extract_dir ;;
+      (*.rar) unrar x -ad "$1" ;;
+      (*.7z) 7za x "$1" ;;
+      (*.deb)
+        mkdir -p "$extract_dir/control"
+        mkdir -p "$extract_dir/data"
+        cd "$extract_dir"; ar vx "../${1}" > /dev/null
+        cd control; tar xzvf ../control.tar.gz
+        cd ../data; tar xzvf ../data.tar.gz
+        cd ..; rm *.tar.gz debian-binary
+        cd ..
+      ;;
+      (*) 
+        echo "extract: '$1' cannot be extracted" 1>&2
+        success=1 
+      ;; 
+    esac
+
+    (( success = $success > 0 ? $success : $? ))
+    (( $success == 0 )) && (( $remove_archive == 0 )) && rm "$1"
+    shift
+  done
 }
+
+alias x=extract
